trigger: none

parameters:
- name: Version
  type: string

pool:
  vmImage: windows-latest

steps:
- checkout: self
  clean: true
- powershell: Write-Host "##vso[build.updatebuildnumber]${{ parameters.Version }}"
  displayName: Setting build number
- task: NuGetToolInstaller@0
  displayName: Install NuGet tool
  inputs:
    versionSpec: 5.x
- powershell: ./Build.ps1 -Version ${{ parameters.Version }}
  displayName: Building node.js.redist packages
- publish: bin
  displayName: Capturing artifacts
  artifact: Packages
- task: NuGetCommand@2
  displayName: Pushing packages to nuget.org
  inputs:
    command: push
    packagesToPush: bin/*.nupkg
    nuGetFeedType: external
    publishFeedCredentials: nuget.org
