name: 🏭 Build

on:
  pull_request:
  push:
    branches:
      - master
      - 'validate/*'
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: The Node.js version to pack
      publish:
        type: boolean
        description: Push to nuget.org

jobs:
  build:
    name: Build ${{ inputs.version || 'sample version' }}
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - run: ./Build.ps1 -Version ${{ inputs.version || '20.18.2' }} -Verbose
        name: 🏗️ Building node.js.redist packages
      - uses: actions/upload-artifact@v7
        with:
          path: bin
          name: Packages
        name: 📢 Publish artifacts

      - run: ./Test.ps1 -Version ${{ inputs.version || '20.18.2' }} -Verbose
        name: 🧪 Test packages

      - uses: NuGet/login@v1
        id: nuget-login
        if: success() && inputs.publish
        with:
          user: ${{ github.repository_owner }}
        name: 🔐 NuGet trusted publishing login

      - name: 🚀 Push NuGet packages
        run: dotnet nuget push bin\*.nupkg --source https://api.nuget.org/v3/index.json --api-key '${{ steps.nuget-login.outputs.NUGET_API_KEY }}'
        if: success() && inputs.publish
